---
abstract: 'Token scheme definition framework for OAuth 2.0'
author:
  - 'Roger Crew <crew@cs.stanford.edu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OAuth2-Scheme
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-OAuth2-Scheme
  repository: git://github.com/wrog/Net-OAuth2-Scheme.git
version: 0.010001_001
